PetarMilikic/online-health-center

OnlineHealthCenter/OnlineHealthCenter.sln
OnlineHealthCenter/Services/Reports/Report.API/Controllers/ReportController.cs
OnlineHealthCenter/Services/Reports/Report.API/Dockerfile
OnlineHealthCenter/Services/Reports/Report.API/Program.cs
OnlineHealthCenter/Services/Reports/Report.API/Reports.API.csproj
OnlineHealthCenter/Services/Reports/Reports.Common/DTOs/CreateReportDTO.cs
OnlineHealthCenter/Services/Reports/Reports.Common/DTOs/ReportBaseDTO.cs
OnlineHealthCenter/Services/Reports/Reports.Common/DTOs/ReportDTO.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Data/Interfaces/IReportContext.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Data/ReportContext.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Data/ReportContextSeed.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Entities/Report.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Extensions/ReportExtensions.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Profiles/ReportProfile.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Reports.Common.csproj
OnlineHealthCenter/Services/Reports/Reports.Common/Repositories/Interfaces/IReportRepository.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Repositories/ReportRepository.cs
OnlineHealthCenter/docker-compose.override.yml
OnlineHealthCenter/docker-compose.yml

**`Done:`**
- Added Docker orchestration support
- Improved Repository and Controller
- Created DTOs and added AutoMapper
- Organized code in `API` and `Common`

Reports.API improvements

---

OnlineHealthCenter/Security/IdentityServer/Controllers/UserController.cs
OnlineHealthCenter/Security/IdentityServer/DTOs/ChangePasswordDTO.cs
OnlineHealthCenter/Security/IdentityServer/Data/EntityTypeConfigurations/Constants/RoleConstants.cs
OnlineHealthCenter/Security/IdentityServer/Data/EntityTypeConfigurations/Constants/UserConstants.cs
OnlineHealthCenter/Security/IdentityServer/Data/EntityTypeConfigurations/RoleConfiguration.cs
OnlineHealthCenter/Security/IdentityServer/Data/EntityTypeConfigurations/UserConfiguration.cs
OnlineHealthCenter/Security/IdentityServer/Data/EntityTypeConfigurations/UserRoleConfiguration.cs
OnlineHealthCenter/Security/IdentityServer/Data/IdentityContext.cs
OnlineHealthCenter/Security/IdentityServer/Migrations/20230125164239_AddedPreconfiguredUsersWithRoles.Designer.cs
OnlineHealthCenter/Security/IdentityServer/Migrations/20230125164239_AddedPreconfiguredUsersWithRoles.cs
OnlineHealthCenter/Security/IdentityServer/Repositories/IdentityRepository.cs
OnlineHealthCenter/Security/IdentityServer/Repositories/Interfaces/IIdentityRepository.cs

- added preconfigured users
- added `changePassword` method

IdentityServer - additional improvements

---

OnlineHealthCenter/Services/Reports/Report.API/Controllers/ReportController.cs
OnlineHealthCenter/Services/Reports/Reports.Common/DTOs/ReportBaseDTO.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Data/ReportContextSeed.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Entities/Report.cs
OnlineHealthCenter/Services/Reports/Reports.Common/Profiles/ReportProfile.cs

**Done**:
- changed `Report` entity and corresponding DTO
- changed seed
- fixed role-based authorization (disjunction instead of conjunction)
> Fixed #59

Reports.API - Entity and Controller changes

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/app-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions.module.ts

WebApp: Created Impressions module

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/doctorEntity.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/impressions.module.ts

Web App: AddImpressionForm created

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/appointment-status.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.ts

Web App: ScheduleForm implemented

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-appointments-scheduleing/appointments-request-form/request-form/request-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-appointments-scheduleing/appointments-request-form/request-form/request-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-appointments-scheduleing/appointments-request-form/request-form/request-form.component.ts

Web App: RequestAppointmentForm improvements

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/index.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/styles.css

Web App: Background color changed

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/package-lock.json
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.html

Add Impression Form Improvement
closes #89

Add Impression Form Improvement

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/app-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.module.ts

WebApp: EmployeeInformation module created

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts

WebApp: EmployeeInformation form

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts

listed all impressions for one doctor 
- updated employee-information-form.component.html
- updated employee-information-form.component.ts
closes #95

WebApp: EmployeeInformation - show impressions

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html

**WebApp: EmployeeInformation** 
- updated employee-information-form.component.html
closes #98

WebApp: EmployeeInformation update

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.ts

WebApp: Created clinic information component

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/application-services/appointments-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/infrastructure/appointments.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/model/appoinement-cancel-request.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/model/appointment-approve-request.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/model/appointment-delete-request.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.ts

WebApp: Appointments Service&UI - Approve and Cancel options implemented

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html

WebApp: Start page style improvements

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/appointments-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/appointments.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.html

WebApp: Create Discount feature/form enabled

---

OnlineHealthCenter/Services/EmployeeInformation/EmployeeInformation.API/Program.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/common/domain/model/doctorEntity.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts

Employee Information Form improvements: GetDoctors method added
- employee-information-form.component.ts
- employee-information-form.component.html
Clinic Information Component small improvements
- clinic-information.component.html
OnlineHealtCenter - EmployeeInformation Service
- Program.cs - Cors setup
closes #114

Web app employee information get doctors

---

OnlineHealthCenter/Services/Impressions/Impressions.API/Program.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/application-services/impressions-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/doctorEntity.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/infrastructure/impressions.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/model/IAddImpressionRequest.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/model/impressionEntity.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.ts

- Impressions Service created 
- Get Impressions method created 
- Listed all impressions on start page
- Online Health Center: Impressions - Cors setup

Web app impressions service

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/package-lock.json
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/package.json
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.ts

WebApp: show impressions form component improvement
closes #127

WebApp: show impressions form component improvement

---

OnlineHealthCenter/Services/Impressions/Impressions.API/Controllers/ImpressionController.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/application-services/impressions-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/infrastructure/impressions.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/model/impression-delete-request.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/model/impressionEntity.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.ts

**Online Health Center - ImpressionController**
-  DeleteImpressionById method improved 
**WebApp:**
- Delete Impression method created (impressions.service.ts)
- Show Impressions Form Component - delete impressions option added 
closes #129

Web app delete impression

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/model/impressionEntity.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.ts

**WebApp - Impressions:**
- Added Date and Time
closes #131

WebApp: Impression date added

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-clinic-information/clinic-information/clinic-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/feature-authentication/login-form/login-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/feature-authentication/login-form/login-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/feature-authentication/registration-form/registration-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/identity-routing.module.ts

- Added button `Register Users` for nurse
- Improved styling for start page

WebApp: added button and improved styling

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/package-lock.json
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.ts

**WebApp - Impressions**
- getting appState implemented 
- show impressions component improvement
closes #144

WebApp: getting appState, show impressions improvements

---

OnlineHealthCenter/Services/Impressions/Impressions.API/Controllers/ImpressionController.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/application-services/impressions-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/domain/infrastructure/impressions.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.ts

**OnlineHealthCenter - Impressions**
- ImpressionsController small changes
**WebApp - Impressions**
- Add impressions implemented
closes #146

Web app add impression implementation

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/app.component.ts

WebApp: Rerouting '\...' to '\start-page'

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/application-services/employee-information-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/infrastructure/employee-information.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts

**WebApp: Employee Information**
- created employee-information service within employee-information module
- implemented Delete Doctor (for nurse role only)
closes #150

WebApp: delete doctor implemented

---

OnlineHealthCenter/Services/EmployeeInformation/EmployeeInformation.API/Controllers/DoctorController.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/application-services/employee-information-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/infrastructure/employee-information.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/model/IAddDoctorRequest.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html

- Add Doctor implemented
closes #152

Web app add doctor

---

OnlineHealthCenter/Services/EmployeeInformation/EmployeeInformation.API/Controllers/DoctorController.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/application-services/employee-information-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/infrastructure/employee-information.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/model/IUpdateDoctorRequest.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-update-doctor/update-doctor-form/update-doctor-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-update-doctor/update-doctor-form/update-doctor-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-update-doctor/update-doctor-form/update-doctor-form.component.ts

- Update Doctor form component created
- Add Doctor small changes 
**OnlineHealthCenter**
- DoctorController small changes
closes #156

Web app update doctor

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/application-services/employee-information-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/domain/model/IAddDoctorRequest.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.ts

- Add Doctor form component  improvement (added id field)
closes #160

WebApp: add doctor improvements

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/domain/application-services/user-facade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/domain/infrastructure/user.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/feature-user-info/show-all-users/show-all-users.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/feature-user-info/show-all-users/show-all-users.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/feature-user-info/show-all-users/show-all-users.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/identity-routing.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/identity/identity.module.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/reports/feature-show-reports/show-reports-form/show-reports-form.component.ts

- Implemented component for showing user details for each user
- Improved filterReports method
Closes #162

WebApp: added show-all-users component

---

OnlineHealthCenter/Services/Appointments/Appointments.API/Controllers/AppointmentsController.cs
OnlineHealthCenter/Services/Appointments/Appointments.Application/Persistance/IAppointmentRepository.cs
OnlineHealthCenter/Services/Appointments/Appointments.Infrastructure/Repositories/AppointmentsRepository.cs
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/app.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/application-services/appointments-fascade.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/domain/infrastructure/appointments.service.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-appointments-scheduleing/appointments-request-form/request-form/request-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.ts

Services& WebApp: Discount and Appointments services general refactor; RequestAppointmentForm & ScheduleForm final arrangement#165

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/application-header/application-header.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-appointments-scheduleing/appointments-request-form/request-form/request-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/schedule-form/schedule-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-update-doctor/update-doctor-form/update-doctor-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-add-impressions/add-impression-form/add-impression-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/impressions/feature-show-impressions/show-impressions-form/show-impressions-form.component.css
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/reports/feature-create-report/create-report-form/create-report-form.component.css

WebApp: Final UI Improvements - Resizeing, Hover&Active button events added

---

OnlineHealthCenter/Services/Impressions/Impressions.API/Controllers/ImpressionController.cs

**Impressions**
- ImpressionController improvement
closes #171

Impressions - Controller final improvement

---

OnlineHealthCenter/Services/Appointments/Appointments.API/Controllers/AppointmentsController.cs
OnlineHealthCenter/Services/Appointments/Appointments.API/Program.cs
OnlineHealthCenter/Services/Appointments/Appointments.API/appsettings.Development.json
OnlineHealthCenter/Services/Appointments/Appointments.Infrastructure/Appointments.Infrastructure.csproj
OnlineHealthCenter/Services/Appointments/Appointments.Infrastructure/Extensions/InfrastructureServiceRegistration.cs
OnlineHealthCenter/Services/Discounts/Discount.Common/Discount.Common.csproj
OnlineHealthCenter/Services/Discounts/Discount.Common/Extensions/DiscountsCommonExtensions.cs
OnlineHealthCenter/Services/Discounts/Discounts.API/Controllers/DiscountController.cs
OnlineHealthCenter/Services/Discounts/Discounts.API/Program.cs
OnlineHealthCenter/Services/Discounts/Discounts.API/appsettings.Development.json
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-appointments-scheduleing/appointments-request-form/request-form/request-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/appointments/feature-show-schedule/create-coupon-form/create-coupon-form/create-coupon-form.component.ts

Services&WebApp: Appointments&Discounts Service - JWT Authorization added

---

OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/employee-information.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-add-doctor/add-doctor-form/add-doctor-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.html
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-employee-information/employee-information-form/employee-information-form.component.ts
OnlineHealthCenter/WebApps/OnlineHealthCenterSPA/src/app/employee-information/feature-update-doctor/update-doctor-form/update-doctor-form.component.html

- Update doctor form component 
- Employee Information form component: Doctors mark rounded
closes #175

Web app employee information final improvements
